### PR TITLE
Fixed path to init.rilmptcp.rc

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <lovaren@gmail.com>

### CODE REVIEW

**Comment by Umeaboy** [comment]
As I mounted the system img to system/ I saw that this file wasn't located in /system/etc/init/ like the proprietary-files.txt describes so I therefor corrected the path.

**Comment by Umeaboy** [comment]
Is it possible to merge?

**Comment by cryptomilk** [comment]
I don't think this is correct. The line copies the file from system root (`/`) on the stock ROM to `/system/etc/init/` in the LineageOS ROM so that the files gets parsed by the init system. If you move the fle to a different place the init system wont pick it up ...

The question is why the file doesn't get copied by you? I suspect that you don't have the file permissions to read it ...

**Comment by Umeaboy** [comment]
Don't know. I'll add the pull output.

**Comment by Umeaboy** [comment]
[Output from extracting blobs from the phone.log](https://github.com/whatawurst/android_device_samsung_beyond2lte/files/5766956/Output.from.extracting.blobs.from.the.phone.log)

**Comment by Umeaboy** [comment]
What can be done?

**Comment by Umeaboy** [comment]
What do you make of it?

**Comment by Umeaboy** [comment]
I can't seem to find it anywhere. If it's meant for RIL (to make calls), why doesn't it exist in the stock rom anymore?

**Comment by Umeaboy** [comment]
This is the stock rom zip I used to extract the blobs from and it doesn't contain that file either:

https://dl2018.sammobile.com/M1FeRi8rLDtcKjE8SjcuTUNdLzwxPk0sMSQnKD0tLFoOARlJUyA5RSJXUkI1UlNMQF9YRFFJTg4EAhYSSVJYR0ZRX0ZaSw../G975FXXS9DTK9_G975FOXM9DTJB_NEE.zip

**Comment by cryptomilk** [comment]
```
$ find beyond2lte/dtk9/unpacked/ -name init.rilmptcp.rc
beyond2lte/dtk9/unpacked/system/init.rilmptcp.rc
```

It is part of `system.img.lz4`

**Comment by Umeaboy** [comment]
> ```
> $ find beyond2lte/dtk9/unpacked/ -name init.rilmptcp.rc
> beyond2lte/dtk9/unpacked/system/init.rilmptcp.rc
> ```
> 
> It is part of `system.img.lz4`

Uuuuuuuhm.

I extracted system.img.lz4 from the DTK9 zip.
I then ran lz4 -d system.img.lz4 system.img
I then ran simg2img system.img system_1.img
I then double clicked and the image mounted on my desktop as _
I then checked in /system/etc/init and there it was, but the extract-files.sh script could not find it either on my phone or in that folder. Check the log I added here.

**Comment by cryptomilk** [comment]
The file is in the root folder (`/`) and not in `/system/etc/init`! `/system/etc/init` is the destination where it is copied to.

**Comment by sailinggalaxians** [comment]
> The file is in the root folder (`/`) and not in `/system/etc/init`! `/system/etc/init` is the destination where it is copied to.

OK, I can accept that, but why then isn't it finding it and pulling it then?

It feels like the extract-files.sh or proprietary-files.txt is wrong.
Just saying.

**Comment by sailinggalaxians** [comment]
No matter how I try it still fails to find it.
proprietary-files.txt has to be wrong.

**Comment by cryptomilk** [comment]
What exactly is the issue you're seeing. Probably you have a log message stating that something is wrong. Post that log snippet ...

**Comment by Umeaboy** [comment]
I have added the log with the Umeaboy account.

To extract them I had to do adb pull system/ and then run .extract-files.sh ~/android_dump/system/
Nothing else worked.

/Kristoffer


19 juni 2021 07:27 av ***@***.***:

**Pull request closed without merging**
